steps:
#Step:1 Install dependencies
- name: 'python:3.11'
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      pip install -r requirements.txt
      pytest --maxfail=1 --disable-warnings -q


# Step 2: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '-t',
    'asia-south2-docker.pkg.dev/bookstore-chatbot-472706/my-repo/my-app:$SHORT_SHA',
    '.'
  ]


# Step 3: Push image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'asia-south2-docker.pkg.dev/bookstore-chatbot-472706/my-repo/my-app:$SHORT_SHA'
  ]

  

# Optional: Step 4 Deploy to Cloud Run (only if you want CI + CD)
# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args:
#     [
#       'run', 'deploy', 'my-app',
#       '--image', 'asia-south2-docker.pkg.dev/bookstore-chatbot-472706/my-repo/my-app:$SHORT_SHA',
#       '--region', 'asia-south2',
#       '--platform', 'managed',
#       '--allow-unauthenticated'
#     ]

# images:
# - 'asia-south2-docker.pkg.dev/bookstore-chatbot-472706/my-repo/my-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

